services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - fast_pdf_network

  pdf-validator:
    build: .
    environment:
      - HTTP_ADDR=:8000
      - MAX_FILE_SIZE_MB=10
      - ENV=production
    networks:
      - fast_pdf_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pdf-validator.rule=PathPrefix(`/extract`)"
      - "traefik.http.services.pdf-validator.loadbalancer.server.port=8000"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

networks:
  fast_pdf_network:
    external: true
